name: Prettier - Check markdown files format

on:
  push:
    paths: README.md
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Install prettier
        run: sudo npm install --global prettier
      - name: Run prettier on Markdown
        run: prettier README.md --check
