name: Prettier - Check HTML, CSS, JS files format

on:
  push:
    paths:
      - *.html
      - style.css
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '10.x'
      - name: Install prettier
        run: sudo npm install --global prettier
      - name: Run prettier on HTML
        run: prettier *.html --check
      - name: Run prettier on CSS
        run: prettier style.css --check
